# Generated by Django 4.1.2 on 2022-10-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_url', models.CharField(default='url of the host', max_length=50, verbose_name='Host')),
                ('short_url', models.CharField(blank=True, default='short url', max_length=50, verbose_name='Short')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
        ),
    ]
